name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout mã nguồn
    - name: Checkout code
      uses: actions/checkout@v4

    # Thiết lập Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Đăng nhập vào Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build và push Docker image
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-ci-cd-demo:latest

    - name: Trigger Render deployment
      if: github.event_name == 'push'
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}